apiVersion: v1
kind: Service
metadata:
  name: $APPLICATION_NAME
  namespace: $APPLICATION_ENVIRONMENT
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: http
  selector:
    app: $APPLICATION_NAME
    environment: $CI_ENVIRONMENT_SLUG