apiVersion: v1
kind: Service
metadata:
  name: cloudsim-lb
  namespace: cloudsim
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      name: http
  selector:
    role: cloudsim