apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::<AWS_ID>:root
      username: root
      groups:
        - system:masters
    - userarn: arn:aws:iam::<AWS_ID>:user/<user>
      username: <user>
      groups:
        - system:masters